inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.5

Rails:
  Enabled: true
Rails/ActionFilter:
  Enabled: true
Rails/ActiveRecordAliases:
  Enabled: true
Rails/ActiveSupportAliases:
  Enabled: true
Rails/ApplicationJob:
  Enabled: true
Rails/ApplicationRecord:
  Enabled: true
Rails/Blank:
  Enabled: true
Rails/CreateTableWithTimestamps:
  Enabled: true
Rails/Date:
  Enabled: true
Rails/Delegate:
  Enabled: true
Rails/DelegateAllowBlank:
  Enabled: true
Rails/DynamicFindBy:
  Enabled: true
Rails/EnumUniqueness:
  Enabled: true
Rails/EnvironmentComparison:
  Enabled: true
Rails/Exit:
  Enabled: true
Rails/FilePath:
  Enabled: true
Rails/FindBy:
  Enabled: true
Rails/FindEach:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: true
Rails/HasManyOrHasOneDependent:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: true
Rails/HttpStatus:
  Enabled: true
Rails/InverseOf:
  Enabled: true
Rails/LexicallyScopedActionFilter:
  Enabled: true
Rails/NotNullColumn:
  Enabled: true
Rails/Output:
  Enabled: true
Rails/OutputSafety:
  Enabled: true
Rails/PluralizationGrammar:
  Enabled: true
Rails/Presence:
  Enabled: true
Rails/Present:
  Enabled: true
Rails/ReadWriteAttribute:
  Enabled: true
Rails/RedundantReceiverInWithOptions:
  Enabled: true
Rails/RelativeDateConstant:
  Enabled: true
Rails/RequestReferer:
  Enabled: true
Rails/ReversibleMigration:
  Enabled: true
Rails/SafeNavigation:
  Enabled: true
Rails/SaveBang:
  Enabled: true
Rails/ScopeArgs:
  Enabled: true
Rails/SkipsModelValidations:
  Enabled: true
Rails/TimeZone:
  Enabled: true
Rails/UniqBeforePluck:
  Enabled: true
Rails/UnknownEnv:
  Enabled: true
Rails/Validation:
  Enabled: true
