version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:4
    ports:
      - 6379:6379
  memcached:
    image: memcached:1
    ports:
      - 11211:11211

volumes:
  db-data:
