version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:4
    ports:
      - 6380:6379
  memcached:
    image: memcached:1
    ports:
      - 11212:11211

volumes:
  db-data:
